### ISSUE TITLE
Wercker is not working after upgrade to Os X Sierra

### ISSUE THREAD

**Issue by BeOleg** [wercker/support#270]
Following issue occurs at `wercker dev` pipeline after upgrading to Os X sierra (latest) both for me and a freelancer with a different mac:

```
unexpected fault address 0xb01dfacedebac1e
fatal error: fault
[signal 0xb code=0x1 addr=0xb01dfacedebac1e pc=0x37fa8b]

goroutine 1 [running]:
runtime.throw(0x8e94f0, 0x5)
	/usr/local/go/src/runtime/panic.go:547 +0x90 fp=0xc8201c2df0 sp=0xc8201c2dd8
runtime.sigpanic()
	/usr/local/go/src/runtime/sigpanic_unix.go:27 +0x2ba fp=0xc8201c2e40 sp=0xc8201c2df0
github.com/wercker/wercker/vendor/github.com/Sirupsen/logrus.Entry.log(0xc82006ebc0, 0xc8202b98f0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xd704, 0xc82030a600, ...)
	/go/src/github.com/wercker/wercker/vendor/github.com/Sirupsen/logrus/entry.go:88 +0xfb fp=0xc8201c2f68 sp=0xc8201c2e40
github.com/wercker/wercker/vendor/github.com/Sirupsen/logrus.(*Entry).Info(0xc82030a4c0, 0xc8201c3018, 0x1, 0x1)
	/go/src/github.com/wercker/wercker/vendor/github.com/Sirupsen/logrus/entry.go:129 +0x8c fp=0xc8201c2fd8 sp=0xc8201c2f68
github.com/wercker/wercker/vendor/github.com/Sirupsen/logrus.(*Entry).Infoln(0xc82030a4c0, 0xc8201c31b8, 0x1, 0x1)
```

Additional information:

- wercker environment: local
- OS: Os X sierra
- Docker environment: boot2docker latest
- Docker machine driver used: virtualbox

If the issue occurs locally, replace this text with a link to a [gist](https://gist.github.com) containing the following:
- `docker version`
```
Client:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        Tue Oct 11 05:27:08 2016
 OS/Arch:      darwin/amd64
 Experimental: true

Server:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        Tue Oct 11 05:27:08 2016
 OS/Arch:      linux/amd64
 Experimental: true # (same happens with stable)
```

- `docker info`
```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.12.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host overlay bridge
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.24-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.951 GiB
Name: moby
ID: BWMZ:RMXO:SWXK:ILME:KYSE:BNWT:WCKY:BUTM:AUAO:QI4P:WSUP:L5B2
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 15
 Goroutines: 27
 System Time: 2016-10-15T16:09:52.80220665Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Username: onit
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Olegs-MacBook-Pro:~ beoleg$ 
```

- `docker-machine version`
```
docker-machine version 0.8.2, build e18a919
```

- `vboxmanage -v` (or fusion equivalent)
```
Olegs-MacBook-Pro:~ beoleg$ vboxmanage -v
5.0.26r108824
```
- entire log of `wercker --debug ...`
```
(nexchange) Olegs-MacBook-Pro:nexchange beoleg$ wercker --debug dev
unexpected fault address 0x22fd4148256a
fatal error: fault
[signal 0xb code=0x1 addr=0x22fd4148256a pc=0x37fa8b]

goroutine 1 [running]:
runtime.throw(0x8e94f0, 0x5)
	/usr/local/go/src/runtime/panic.go:547 +0x90 fp=0xc8201c4df0 sp=0xc8201c4dd8
runtime.sigpanic()
	/usr/local/go/src/runtime/sigpanic_unix.go:27 +0x2ba fp=0xc8201c4e40 sp=0xc8201c4df0
github.com/wercker/wercker/vendor/github.com/Sirupsen/logrus.Entry.log(0xc820070b80, 0xc8202b9a10, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xd704, 0xc82030c780, ...)
	/go/src/github.com/wercker/wercker/vendor/github.com/Sirupsen/logrus/entry.go:88 +0xfb fp=0xc8201c4f68 sp=0xc8201c4e40
github.com/wercker/wercker/vendor/github.com/Sirupsen/logrus.(*Entry).Info(0xc82030c640, 0xc8201c5018, 0x1, 0x1)
	/go/src/github.com/wercker/wercker/vendor/github.com/Sirupsen/logrus/entry.go:129 +0x8c fp=0xc8201c4fd8 sp=0xc8201c4f68
github.com/wercker/wercker/vendor/github.com/Sirupsen/logrus.(*Entry).Infoln(0xc82030c640, 0xc8201c51b8, 0x1, 0x1)
	/go/src/github.com/wercker/wercker/vendor/github.com/Sirupsen/logrus/entry.go:220 +0x120 fp=0xc8201c5058 sp=0xc8201c4fd8
github.com/wercker/wercker/vendor/github.com/Sirupsen/logrus.(*Entry).Println(0xc82030c640, 0xc8201c51b8, 0x1, 0x1)
	/go/src/github.com/wercker/wercker/vendor/github.com/Sirupsen/logrus/entry.go:225 +0x3f fp=0xc8201c5080 sp=0xc8201c5058
github.com/wercker/wercker/docker.guessAndUpdateDockerOptions(0xc8201fbf90, 0xc8202b8d20)
	/go/src/github.com/wercker/wercker/docker/options.go:48 +0x2a6 fp=0xc8201c53d0 sp=0xc8201c5080
github.com/wercker/wercker/docker.NewDockerOptions(0xf7e938, 0xc8202fea40, 0xc8202b8d20, 0xc820318000, 0x0, 0x0)
	/go/src/github.com/wercker/wercker/docker/options.go:122 +0x2c2 fp=0xc8201c5488 sp=0xc8201c53d0
github.com/wercker/wercker/cmd.glob.func2(0xc8200e09c0)
	/go/src/github.com/wercker/wercker/cmd/main.go:91 +0x607 fp=0xc8201c56e0 sp=0xc8201c5488
github.com/wercker/wercker/vendor/github.com/codegangsta/cli.Command.Run(0x8e9050, 0x3, 0x0, 0x0, 0x992620, 0x1f, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/wercker/wercker/vendor/github.com/codegangsta/cli/command.go:113 +0x10b0 fp=0xc8201c5b38 sp=0xc8201c56e0
github.com/wercker/wercker/vendor/github.com/codegangsta/cli.(*App).Run(0xc8202f0000, 0xc82006c0c0, 0x3, 0x3, 0x0, 0x0)
	/go/src/github.com/wercker/wercker/vendor/github.com/codegangsta/cli/app.go:156 +0xbe9 fp=0xc8201c5ec8 sp=0xc8201c5b38
main.main()
	/go/src/github.com/wercker/wercker/main.go:25 +0x49 fp=0xc8201c5f00 sp=0xc8201c5ec8
runtime.main()
	/usr/local/go/src/runtime/proc.go:188 +0x2b0 fp=0xc8201c5f50 sp=0xc8201c5f00
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc8201c5f58 sp=0xc8201c5f50

goroutine 18 [syscall]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:116 +0x132
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 19 [select, locked to thread]:
runtime.gopark(0xa74a70, 0xc820025728, 0x8eb4f0, 0x6, 0x18, 0x2)
	/usr/local/go/src/runtime/proc.go:262 +0x163
runtime.selectgoImpl(0xc820025728, 0x0, 0x18)
	/usr/local/go/src/runtime/select.go:392 +0xa67
runtime.selectgo(0xc820025728)
	/usr/local/go/src/runtime/select.go:215 +0x12
runtime.ensureSigM.func1()
	/usr/local/go/src/runtime/signal1_unix.go:279 +0x32c
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 20 [chan receive]:
github.com/wercker/wercker/util.(*SignalMonkey).Register.func1(0xc820070bc0)
	/go/src/github.com/wercker/wercker/util/signal.go:95 +0x76
created by github.com/wercker/wercker/util.(*SignalMonkey).Register
	/go/src/github.com/wercker/wercker/util/signal.go:106 +0x111

goroutine 21 [chan receive]:
github.com/wercker/wercker/util.(*SignalMonkey).Register.func1(0xc820070c00)
	/go/src/github.com/wercker/wercker/util/signal.go:95 +0x76
created by github.com/wercker/wercker/util.(*SignalMonkey).Register
	/go/src/github.com/wercker/wercker/util/signal.go:106 +0x111
```

**Comment by BeOleg** [comment]
Anybody home?
