### ISSUE TITLE
ewok: cli not supporting the services syntax as stated in docs

### ISSUE THREAD

**Issue by qraynaud** [wercker/support#32]
The CLI does not support the full syntax described in the documentation here: http://devcenter.wercker.com/docs/services/advanced-services.html.

As soon as I try the `id:` syntax it fails with the following error:
```
panic: interface conversion: interface is string, not yaml.MapSlice [recovered]
 panic: interface conversion: interface is string, not yaml.MapSlice [recovered]
 panic: interface conversion: interface is string, not yaml.MapSlice [recovered]
 panic: interface conversion: interface is string, not yaml.MapSlice

goroutine 1 [running]:
gopkg.in/yaml%2ev2.handleErr(0xc20811edb0)
 /gopath/src/github.com/wercker/sentcli/_vendor/src/gopkg.in/yaml.v2/yaml.go:154 +0xc6
gopkg.in/yaml%2ev2.handleErr(0xc20811e8f0)
 /gopath/src/github.com/wercker/sentcli/_vendor/src/gopkg.in/yaml.v2/yaml.go:154 +0xc6
gopkg.in/yaml%2ev2.handleErr(0xc20811e110)
 /gopath/src/github.com/wercker/sentcli/_vendor/src/gopkg.in/yaml.v2/yaml.go:154 +0xc6
main.(*RawStepConfig).UnmarshalYAML(0xc20804e240, 0xc20800bf20, 0x0, 0x0)
 /gopath/src/github.com/wercker/sentcli/config.go:94 +0x24e
gopkg.in/yaml%2ev2.(*decoder).callUnmarshaler(0xc2080a1340, 0xc20805fe60, 0x7fb9827f7be8, 0xc20804e240, 0xc20804e240)
 /gopath/src/github.com/wercker/sentcli/_vendor/src/gopkg.in/yaml.v2/decode.go:235 +0x150
gopkg.in/yaml%2ev2.(*decoder).prepare(0xc2080a1340, 0xc20805fe60, 0x929fe0, 0xc20804e240, 0xd9, 0x0, 0x0, 0x0, 0x915440)
 /gopath/src/github.com/wercker/sentcli/_vendor/src/gopkg.in/yaml.v2/decode.go:269 +0x456
gopkg.in/yaml%2ev2.(*decoder).unmarshal(0xc2080a1340, 0xc20805fe60, 0x915440, 0xc20804e238, 0xd6, 0xd6)
 /gopath/src/github.com/wercker/sentcli/_vendor/src/gopkg.in/yaml.v2/decode.go:284 +0xc4
gopkg.in/yaml%2ev2.(*decoder).sequence(0xc2080a1340, 0xc20805fe00, 0x823860, 0xc20800be40, 0xd7, 0x823860)
 /gopath/src/github.com/wercker/sentcli/_vendor/src/gopkg.in/yaml.v2/decode.go:498 +0x2c8
gopkg.in/yaml%2ev2.(*decoder).unmarshal(0xc2080a1340, 0xc20805fe00, 0x823860, 0xc20800be40, 0xd7, 0x0)
 /gopath/src/github.com/wercker/sentcli/_vendor/src/gopkg.in/yaml.v2/decode.go:294 +0x16f
gopkg.in/yaml%2ev2.(*decoder).document(0xc2080a1340, 0xc20805ff20, 0x823860, 0xc20800be40, 0xd7, 0x63712c)
 /gopath/src/github.com/wercker/sentcli/_vendor/src/gopkg.in/yaml.v2/decode.go:304 +0xa7
gopkg.in/yaml%2ev2.(*decoder).unmarshal(0xc2080a1340, 0xc20805ff20, 0x823860, 0xc20800be40, 0xd7, 0xd7)
 /gopath/src/github.com/wercker/sentcli/_vendor/src/gopkg.in/yaml.v2/decode.go:280 +0x62
gopkg.in/yaml%2ev2.Unmarshal(0xc208094e20, 0xe, 0x10, 0x80f160, 0xc20800be40, 0x0, 0x0)
 /gopath/src/github.com/wercker/sentcli/_vendor/src/gopkg.in/yaml.v2/yaml.go:91 +0x2a3
main.(*RawPipelineConfig).UnmarshalYAML(0xc20804e130, 0xc20800b560, 0x0, 0x0)
 /gopath/src/github.com/wercker/sentcli/config.go:180 +0x3ed
gopkg.in/yaml%2ev2.(*decoder).callUnmarshaler(0xc2080a0e40, 0xc20805e4e0, 0x7fb9827f7b48, 0xc20804e130, 0xc20804e130)
 /gopath/src/github.com/wercker/sentcli/_vendor/src/gopkg.in/yaml.v2/decode.go:235 +0x150
gopkg.in/yaml%2ev2.(*decoder).prepare(0xc2080a0e40, 0xc20805e4e0, 0x902760, 0xc20804e130, 0xd9, 0x0, 0x0, 0x0, 0xc208090000)
 /gopath/src/github.com/wercker/sentcli/_vendor/src/gopkg.in/yaml.v2/decode.go:269 +0x456
gopkg.in/yaml%2ev2.(*decoder).unmarshal(0xc2080a0e40, 0xc20805e4e0, 0x8e8ae0, 0xc20805fbc8, 0xd6, 0xc20805fbc8)
 /gopath/src/github.com/wercker/sentcli/_vendor/src/gopkg.in/yaml.v2/decode.go:284 +0xc4
gopkg.in/yaml%2ev2.(*decoder).mappingStruct(0xc2080a0e40, 0xc20805e300, 0x96e6c0, 0xc20805fbc0, 0xd9, 0x1005d3289)
 /gopath/src/github.com/wercker/sentcli/_vendor/src/gopkg.in/yaml.v2/decode.go:635 +0x732
gopkg.in/yaml%2ev2.(*decoder).mapping(0xc2080a0e40, 0xc20805e300, 0x96e6c0, 0xc20805fbc0, 0xd9, 0x96e6c0)
 /gopath/src/github.com/wercker/sentcli/_vendor/src/gopkg.in/yaml.v2/decode.go:513 +0xcc3
gopkg.in/yaml%2ev2.(*decoder).unmarshal(0xc2080a0e40, 0xc20805e300, 0x96e6c0, 0xc20805fbc0, 0xd9, 0xc20805fbc0)
 /gopath/src/github.com/wercker/sentcli/_vendor/src/gopkg.in/yaml.v2/decode.go:292 +0x138
gopkg.in/yaml%2ev2.func·001(0x915280, 0xc20805fbc0, 0x0, 0x0)
 /gopath/src/github.com/wercker/sentcli/_vendor/src/gopkg.in/yaml.v2/decode.go:228 +0x105
main.(*RawConfig).UnmarshalYAML(0xc20804e0b8, 0xc20800b500, 0x0, 0x0)
 /gopath/src/github.com/wercker/sentcli/config.go:226 +0x10f
gopkg.in/yaml%2ev2.(*decoder).callUnmarshaler(0xc2080a0e40, 0xc20805e300, 0x7fb9827f7ad0, 0xc20804e0b8, 0xc20804e0b8)
 /gopath/src/github.com/wercker/sentcli/_vendor/src/gopkg.in/yaml.v2/decode.go:235 +0x150
gopkg.in/yaml%2ev2.(*decoder).prepare(0xc2080a0e40, 0xc20805e300, 0x93e4e0, 0xc20804e0b8, 0xd9, 0x0, 0x0, 0x0, 0x1)
 /gopath/src/github.com/wercker/sentcli/_vendor/src/gopkg.in/yaml.v2/decode.go:269 +0x456
gopkg.in/yaml%2ev2.(*decoder).unmarshal(0xc2080a0e40, 0xc20805e300, 0x93e4e0, 0xc20804e0b8, 0xd9, 0x0)
 /gopath/src/github.com/wercker/sentcli/_vendor/src/gopkg.in/yaml.v2/decode.go:284 +0xc4
gopkg.in/yaml%2ev2.(*decoder).document(0xc2080a0e40, 0xc20805e240, 0x93e4e0, 0xc20804e0b8, 0xd9, 0x63712c)
 /gopath/src/github.com/wercker/sentcli/_vendor/src/gopkg.in/yaml.v2/decode.go:304 +0xa7
gopkg.in/yaml%2ev2.(*decoder).unmarshal(0xc2080a0e40, 0xc20805e240, 0x93e4e0, 0xc20804e0b8, 0xd9, 0xd9)
 /gopath/src/github.com/wercker/sentcli/_vendor/src/gopkg.in/yaml.v2/decode.go:280 +0x62
gopkg.in/yaml%2ev2.Unmarshal(0xc208080f00, 0x290, 0x490, 0x939980, 0xc20804e0b8, 0x0, 0x0)
 /gopath/src/github.com/wercker/sentcli/_vendor/src/gopkg.in/yaml.v2/yaml.go:91 +0x2a3
main.ConfigFromYaml(0xc208080f00, 0x290, 0x490, 0x493500, 0x0, 0x0)
 /gopath/src/github.com/wercker/sentcli/config.go:297 +0x9a
main.(*Runner).GetConfig(0xc2080a0d80, 0xc20811f290, 0x0, 0x0, 0x0, 0x0)
 /gopath/src/github.com/wercker/sentcli/runner.go:232 +0x15b
main.(*Runner).SetupEnvironment(0xc2080a0d80, 0x7fb9827e3be8, 0xc20802a990, 0x0, 0x0, 0x0)
 /gopath/src/github.com/wercker/sentcli/runner.go:455 +0x7a0
main.executePipeline(0xc20800da00, 0xacff80, 0x0, 0x0)
 /gopath/src/github.com/wercker/sentcli/main.go:796 +0xb98
main.cmdBuild(0xc20800da00, 0x0, 0x0)
 /gopath/src/github.com/wercker/sentcli/main.go:330 +0x6d
main.func·001(0xc208032000)
 /gopath/src/github.com/wercker/sentcli/main.go:39 +0x2c4
github.com/codegangsta/cli.Command.Run(0x9b9650, 0x5, 0x9b9030, 0x1, 0x9db7b0, 0xf, 0x0, 0x0, 0x0, 0x0, ...)
 /gopath/src/github.com/wercker/sentcli/_vendor/src/github.com/codegangsta/cli/command.go:113 +0x105a
github.com/codegangsta/cli.(*App).Run(0xc20801e8f0, 0xc20800a000, 0x2, 0x2, 0x0, 0x0)
 /gopath/src/github.com/wercker/sentcli/_vendor/src/github.com/codegangsta/cli/app.go:156 +0xd19
main.main()
 /gopath/src/github.com/wercker/sentcli/main.go:295 +0x4e6

goroutine 5 [syscall]:
os/signal.loop()
 /goroot/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
 /goroot/src/os/signal/signal_unix.go:27 +0x35

goroutine 6 [chan receive]:
main.func·038()
 /gopath/src/github.com/wercker/sentcli/signal.go:81 +0x8b
created by main.(*SignalMonkey).Register
 /gopath/src/github.com/wercker/sentcli/signal.go:92 +0x190

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
 /goroot/src/runtime/asm_amd64.s:2232 +0x1
```

**Comment by flenter** [comment]
Thank you for reporting, can you post the wercker.yml you were using that failed (and the version of the wercker command)? 

I've tried several combinations and have been unable to reproduce the issue.

**Comment by qraynaud** [comment]
Ok, I was on the previous version. It works fine now. Sorry…

**Comment by qraynaud** [comment]
Ok, in fact it works on root but not on pipelines:

```yaml
services:
- id: elasticsearch
```

is ok but not:

```yaml
build:
  services:
  - id: elasticsearch
```

**Comment by mies** [comment]
@qraynaud thanks for pointing that out we're going to have have a look /cc @termie

**Comment by hatchan** [comment]
We've fixed the issue. You should now be able to use the services section within a pipeline.
