### ISSUE TITLE
wercker-api: resource not found (status code: 404)

### ISSUE THREAD

**Issue by nathanpalmer** [wercker/support#76]
I can't seem to get 1 successful build. Each time I try I'm running into this error.

```
DEBU[0428]   events|   WerckerYamlContents string = box: nodesource/trusty
build:
  steps:
    - npm-install
    - bower-install
    - script:
        name: run ember tests
        code: |
          ember test

ERRO[0428]     main| --> Step failed: setup environment
INFO[0428]  literal| [x] stderr "wercker-api: resource not found (status code: 404)\n"
PANI[0428]     root| wercker-api: resource not found (status code: 404)
DEBU[0428]   events| BuildFinished
DEBU[0428]   events|   Box *main.Box
DEBU[0428]   events|   Result string = failed
DEBU[0428]   events| FullPipelineFinished
DEBU[0428]   events|   AfterStepSuccessful bool = false
DEBU[0428]   events|   MainSuccessful bool = false
DEBU[0428]   events|   RanAfterSteps bool = false
panic: (*logrus.Entry) (0x596840,0x2089afa40)

goroutine 1 [running]:
github.com/Sirupsen/logrus.(*Entry).log(0x2089afa40, 0x0, 0x2089afb40, 0x32)
	/gopath/src/github.com/wercker/sentcli/_vendor/src/github.com/Sirupsen/logrus/entry.go:103 +0x634
github.com/Sirupsen/logrus.(*Entry).Panic(0x2089afa40, 0x208e8b208, 0x1, 0x1)
	/gopath/src/github.com/wercker/sentcli/_vendor/src/github.com/Sirupsen/logrus/entry.go:148 +0x7f
github.com/Sirupsen/logrus.(*Entry).Panicln(0x2089afa40, 0x208e8b558, 0x1, 0x1)
	/gopath/src/github.com/wercker/sentcli/_vendor/src/github.com/Sirupsen/logrus/entry.go:241 +0x12b
github.com/Sirupsen/logrus.(*Logger).Panicln(0x20896ab40, 0x208e8b558, 0x1, 0x1)
	/gopath/src/github.com/wercker/sentcli/_vendor/src/github.com/Sirupsen/logrus/logger.go:160 +0xdf
main.(*SoftExit).Exit(0x208e8b410, 0x208e8b558, 0x1, 0x1, 0x0, 0x0)
	/gopath/src/github.com/wercker/sentcli/main.go:307 +0x6f
main.executePipeline(0x20899ec00, 0x6cc518, 0x0, 0x0)
	/gopath/src/github.com/wercker/sentcli/main.go:811 +0x109d
main.cmdBuild(0x20899ec00, 0x0, 0x0)
	/gopath/src/github.com/wercker/sentcli/main.go:330 +0x6d
main.func·001(0x208946000)
	/gopath/src/github.com/wercker/sentcli/main.go:39 +0x2c4
github.com/codegangsta/cli.Command.Run(0x5b7170, 0x5, 0x5b6b50, 0x1, 0x5d9250, 0xf, 0x0, 0x0, 0x0, 0x0, ...)
	/gopath/src/github.com/wercker/sentcli/_vendor/src/github.com/codegangsta/cli/command.go:113 +0x105a
github.com/codegangsta/cli.(*App).Run(0x208950820, 0x208916000, 0x3, 0x3, 0x0, 0x0)
	/gopath/src/github.com/wercker/sentcli/_vendor/src/github.com/codegangsta/cli/app.go:156 +0xd19
main.main()
	/gopath/src/github.com/wercker/sentcli/main.go:295 +0x4e6

goroutine 5 [syscall, 7 minutes]:
os/signal.loop()
	/goroot/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/goroot/src/os/signal/signal_unix.go:27 +0x35

goroutine 6 [chan receive, 7 minutes]:
main.func·038()
	/gopath/src/github.com/wercker/sentcli/signal.go:81 +0x8b
created by main.(*SignalMonkey).Register
	/gopath/src/github.com/wercker/sentcli/signal.go:92 +0x190

goroutine 28 [semacquire, 3 minutes]:
sync.(*Cond).Wait(0x208946c30)
	/goroot/src/sync/cond.go:62 +0x9e
io.(*pipe).read(0x208946c00, 0x208c8c002, 0x5fe, 0x5fe, 0x0, 0x0, 0x0)
	/goroot/src/io/pipe.go:52 +0x303
io.(*PipeReader).Read(0x208954108, 0x208c8c002, 0x5fe, 0x5fe, 0x0, 0x0, 0x0)
	/goroot/src/io/pipe.go:134 +0x5b
encoding/json.(*Decoder).readValue(0x208c3e000, 0x2088d609f, 0x0, 0x0)
	/goroot/src/encoding/json/stream.go:124 +0x5e1
encoding/json.(*Decoder).Decode(0x208c3e000, 0x4e4180, 0x208c6b600, 0x0, 0x0)
	/goroot/src/encoding/json/stream.go:44 +0x7b
main.emitStatus(0x2208b0ef90, 0x208954108, 0x20899ec00)
	/gopath/src/github.com/wercker/sentcli/box.go:530 +0x16d
created by main.(*Box).Fetch
	/gopath/src/github.com/wercker/sentcli/box.go:446 +0x788

goroutine 13 [IO wait, 7 minutes]:
net.(*pollDesc).Wait(0x2089ee370, 0x72, 0x0, 0x0)
	/goroot/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0x2089ee370, 0x0, 0x0)
	/goroot/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0x2089ee310, 0x2089e6c00, 0x400, 0x400, 0x0, 0x220891eef0, 0x208944cc8)
	/goroot/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0x208954060, 0x2089e6c00, 0x400, 0x400, 0x0, 0x0, 0x0)
	/goroot/src/net/net.go:121 +0xdc
crypto/tls.(*block).readFromUntil(0x2089b62d0, 0x2208922030, 0x208954060, 0x5, 0x0, 0x0)
	/goroot/src/crypto/tls/conn.go:454 +0xe6
crypto/tls.(*Conn).readRecord(0x2089c0000, 0x17, 0x0, 0x0)
	/goroot/src/crypto/tls/conn.go:539 +0x2da
crypto/tls.(*Conn).Read(0x2089c0000, 0x208a2e000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/goroot/src/crypto/tls/conn.go:904 +0x166
net/http.noteEOFReader.Read(0x22089228a8, 0x2089c0000, 0x2089f41b8, 0x208a2e000, 0x1000, 0x1000, 0x4aada0, 0x0, 0x0)
	/goroot/src/net/http/transport.go:1270 +0x6e
net/http.(*noteEOFReader).Read(0x2089f2320, 0x208a2e000, 0x1000, 0x1000, 0x20891e000, 0x0, 0x0)
	<autogenerated>:125 +0xd4
bufio.(*Reader).fill(0x2089f0660)
	/goroot/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).Peek(0x2089f0660, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/goroot/src/bufio/bufio.go:132 +0xf0
net/http.(*persistConn).readLoop(0x2089f4160)
	/goroot/src/net/http/transport.go:842 +0xa4
created by net/http.(*Transport).dialConn
	/goroot/src/net/http/transport.go:660 +0xc9f

goroutine 14 [select, 7 minutes]:
net/http.(*persistConn).writeLoop(0x2089f4160)
	/goroot/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
	/goroot/src/net/http/transport.go:661 +0xcbc

goroutine 32 [select, 3 minutes]:
net/http.(*persistConn).writeLoop(0x2089f4e70)
	/goroot/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
	/goroot/src/net/http/transport.go:661 +0xcbc

goroutine 31 [IO wait, 3 minutes]:
net.(*pollDesc).Wait(0x2089efd40, 0x72, 0x0, 0x0)
	/goroot/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0x2089efd40, 0x0, 0x0)
	/goroot/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0x2089efce0, 0x208a8b800, 0x800, 0x800, 0x0, 0x220891eef0, 0x208c00070)
	/goroot/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0x208954218, 0x208a8b800, 0x800, 0x800, 0x0, 0x0, 0x0)
	/goroot/src/net/net.go:121 +0xdc
crypto/tls.(*block).readFromUntil(0x208c1b680, 0x2208922030, 0x208954218, 0x5, 0x0, 0x0)
	/goroot/src/crypto/tls/conn.go:454 +0xe6
crypto/tls.(*Conn).readRecord(0x2089c1b80, 0x17, 0x0, 0x0)
	/goroot/src/crypto/tls/conn.go:539 +0x2da
crypto/tls.(*Conn).Read(0x2089c1b80, 0x208c40000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/goroot/src/crypto/tls/conn.go:904 +0x166
net/http.noteEOFReader.Read(0x22089228a8, 0x2089c1b80, 0x2089f4ec8, 0x208c40000, 0x1000, 0x1000, 0x4aada0, 0x0, 0x0)
	/goroot/src/net/http/transport.go:1270 +0x6e
net/http.(*noteEOFReader).Read(0x208bb2cc0, 0x208c40000, 0x1000, 0x1000, 0x20891e000, 0x0, 0x0)
	<autogenerated>:125 +0xd4
bufio.(*Reader).fill(0x208972ea0)
	/goroot/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).Peek(0x208972ea0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/goroot/src/bufio/bufio.go:132 +0xf0
net/http.(*persistConn).readLoop(0x2089f4e70)
	/goroot/src/net/http/transport.go:842 +0xa4
created by net/http.(*Transport).dialConn
	/goroot/src/net/http/transport.go:660 +0xc9f

goroutine 23 [sleep]:
net.func·019()
	/goroot/src/net/dnsclient_unix.go:240 +0x5a
created by net.loadConfig
	/goroot/src/net/dnsclient_unix.go:269 +0x20c

goroutine 56 [IO wait]:
net.(*pollDesc).Wait(0x208e82530, 0x72, 0x0, 0x0)
	/goroot/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0x208e82530, 0x0, 0x0)
	/goroot/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0x208e824d0, 0x208a96c00, 0x400, 0x400, 0x0, 0x220891eef0, 0x208ad6610)
	/goroot/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0x2089543c8, 0x208a96c00, 0x400, 0x400, 0x0, 0x0, 0x0)
	/goroot/src/net/net.go:121 +0xdc
crypto/tls.(*block).readFromUntil(0x208c1a5d0, 0x2208922030, 0x2089543c8, 0x5, 0x0, 0x0)
	/goroot/src/crypto/tls/conn.go:454 +0xe6
crypto/tls.(*Conn).readRecord(0x2089c18c0, 0x17, 0x0, 0x0)
	/goroot/src/crypto/tls/conn.go:539 +0x2da
crypto/tls.(*Conn).Read(0x2089c18c0, 0x208e94000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/goroot/src/crypto/tls/conn.go:904 +0x166
net/http.noteEOFReader.Read(0x22089228a8, 0x2089c18c0, 0x208b3a268, 0x208e94000, 0x1000, 0x1000, 0x2089ae980, 0x0, 0x0)
	/goroot/src/net/http/transport.go:1270 +0x6e
net/http.(*noteEOFReader).Read(0x208a869a0, 0x208e94000, 0x1000, 0x1000, 0x20891e000, 0x0, 0x0)
	<autogenerated>:125 +0xd4
bufio.(*Reader).fill(0x208b898c0)
	/goroot/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).Peek(0x208b898c0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/goroot/src/bufio/bufio.go:132 +0xf0
net/http.(*persistConn).readLoop(0x208b3a210)
	/goroot/src/net/http/transport.go:842 +0xa4
created by net/http.(*Transport).dialConn
	/goroot/src/net/http/transport.go:660 +0xc9f

goroutine 57 [select]:
net/http.(*persistConn).writeLoop(0x208b3a210)
	/goroot/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
	/goroot/src/net/http/transport.go:661 +0xcbc
```

**Comment by flenter** [comment]
The problem is that the step bower-install could not be found (there's no wercker/bower-install step). There are several users who've created a bower-install step: https://app.wercker.com/#search/steps/bower-install

So changing `bower-install` into `plasticine/bower-install` should solve this problem.

Also: the next release of the CLI will display `The step bower-install was not found` instead of `wercker-api resource not found`

**Comment by nathanpalmer** [comment]
Thanks. That's probably it, an updated error message would be great!
